#!/bin/bash
# Imports a virtual machine and configures the VM disc to be multiattach
# This means changes to the disc are stored in ~/VirtualBox VMs

vmname="alpha"
vmdkfile="/local/VM/cosc264/$vmname-disk1.vmdk"
ovafile="/local/VM/cosc264/$vmname.ova"

vboxmanage import $ovafile
vboxmanage modifyvm $vmname --sataport0 $vmdkfile
vboxmanage modifyvm $vmname --sataport0 none
vboxmanage modifyhd $vmdkfile --type multiattach
vboxmanage modifyvm $vmname --sataport0 $vmdkfile
