#!/bin/bash

# Because there's no control over the name of the host only adapter that's
# created, there is the potential we end up creating more than we need if some
# already exist
#
# Steven Sykes 08-02-2018

# Delete any previous vboxnets
for adapter in {0..20}; do
  vboxmanage hostonlyif remove vboxnet$adapter
done

# Create all our adapters after deleting older ones...
for adapter in {0..17}; do
  vboxmanage hostonlyif create
done

# ... and delete the vboxnet host only adapters we don't use
#vboxmanage hostonlyif remove vboxnet0
#vboxmanage hostonlyif remove vboxnet8
#vboxmanage hostonlyif remove vboxnet9

# Configure adapters for COSC264
for adapter in {1..7}; do
  vboxmanage hostonlyif ipconfig vboxnet$adapter --ip 192.168.$((10+$adapter)).254 --netmask 255.255.255.0
done

# Configure adapters for COSC362
vboxmanage hostonlyif ipconfig vboxnet0 --ip 10.0.1.1 --netmask 255.255.255.0
vboxmanage hostonlyif ipconfig vboxnet8 --ip 10.0.1.2 --netmask 255.255.255.0
vboxmanage hostonlyif ipconfig vboxnet9 --ip 10.0.1.3 --netmask 255.255.255.0

# Configure adapters for COSC364
vboxmanage hostonlyif ipconfig vboxnet10 --ip 144.10.64.254 --netmask 255.255.255.0
vboxmanage hostonlyif ipconfig vboxnet11 --ip 144.10.65.254 --netmask 255.255.255.0
vboxmanage hostonlyif ipconfig vboxnet12 --ip 144.10.66.254 --netmask 255.255.255.0
vboxmanage hostonlyif ipconfig vboxnet13 --ip 10.2.0.254    --netmask 255.255.255.0
vboxmanage hostonlyif ipconfig vboxnet14 --ip 68.22.1.254   --netmask 255.255.255.0
vboxmanage hostonlyif ipconfig vboxnet15 --ip 77.14.6.254   --netmask 255.255.255.0
vboxmanage hostonlyif ipconfig vboxnet16 --ip 77.14.7.254   --netmask 255.255.255.0
